name-template: "v$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🔥 Breaking Changes"
    labels:
      - "breaking"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "refactor"
      - "chore"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
      - "refactor"
  patch:
    labels:
      - "fix"
      - "chore"
autolabeler:
  - label: "feature"
    branch:
      - "/feature[\/|-].+/"
      - "/feat[\/|-].+/"
  - label: "enhancement"
    branch:
      - "/enhancement[\/|-].+/"
      - "/enhance[\/|-].+/"
  - label: "fix"
    branch:
      - "/fix[\/|-].+/"
      - "/bugfix[\/|-].+/"
  - label: "refactor"
    branch:
      - "/refactor[\/|-].+/"
  - label: "chore"
    branch:
      - "/chore[\/|-].+/"
template: |
  ## What's Changed

  $CHANGES
