# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

#use_frameworks!

target 'tempo-ironsource-mediation-adapter' do
  pod 'tempo-ios-ironsource-mediation', :path => '../'
  #pod 'IronSourceSDK', '7.3.0.0'
  #pod 'TempoSDK', '1.0.3'
  
end
