name: Release to CocoaPods

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  push-pod:
    runs-on: macos-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # Using the podspec, push the latest version of the pod to CocoaPod
      - name: Push Pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push ${{ env.PODSPEC_PATH }} --allow-warnings --verbose
